application: wrook
version: 6
runtime: python
api_version: 1

default_expiration: "21d"

handlers:
- url: /_admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /stylesheets
  static_dir: stylesheets
  expiration: "21d"

- url: /scripts
  static_dir: scripts
  expiration: "21d"

- url: /images
  static_dir: images
  expiration: "21d"

- url: /apidoc
  static_dir: apidoc
  expiration: "21d"

- url: /_flushcache
  script: flushcache.py

- url: /console/static
  static_dir: console/app/view/static

- url: /console.*
  script: console/app/console.py

- url: /
  script: wrook.py

- url: .*
  script: wrook.py

- url: /.*
  script: wrook.py


